version: '3.5'

services:
  api1:
    image: james1515/rinha-de-backend:latest 
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=persondatabase
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
  pgadmi:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "16543:80"